# Generated by Django 3.2.5 on 2021-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField(max_length=16, unique=True)),
                ('uid', models.BigIntegerField(max_length=16)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CorpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(max_length=12, unique=True)),
                ('license_dsid', models.BigIntegerField(max_length=16, unique=True)),
                ('intro', models.CharField(max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsid', models.BigIntegerField(max_length=16, unique=True)),
                ('sequence', models.CharField(max_length=256, null=True)),
                ('type', models.SmallIntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField(max_length=16, unique=True)),
                ('dname', models.CharField(max_length=16)),
                ('dpath', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(max_length=12, unique=True)),
                ('college', models.CharField(max_length=16, null=True)),
                ('major', models.CharField(max_length=16, null=True)),
                ('degree', models.CharField(max_length=4, null=True)),
                ('grade', models.SmallIntegerField(max_length=4, null=True)),
                ('intro', models.CharField(max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_id', models.BigIntegerField(max_length=12, unique=True)),
                ('path', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField(max_length=16, unique=True)),
                ('uid', models.BigIntegerField(max_length=16)),
                ('cr_time', models.DateTimeField()),
                ('st_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.SmallIntegerField(max_length=1, null=1)),
                ('title', models.CharField(max_length=18)),
                ('intro', models.CharField(max_length=3000, null=True)),
                ('pro_dsid', models.BigIntegerField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.BigIntegerField(max_length=16, unique=True)),
                ('uid', models.BigIntegerField(max_length=16)),
                ('pid', models.BigIntegerField(max_length=16)),
                ('status', models.SmallIntegerField(max_length=1)),
                ('intro', models.CharField(max_length=3000, null=True)),
                ('solution_dsid', models.BigIntegerField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(max_length=12, unique=True)),
                ('account', models.CharField(max_length=16, unique=True)),
                ('pwd', models.CharField(max_length=16)),
                ('account_type', models.SmallIntegerField(default=3, max_length=1)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(max_length=12, unique=True)),
                ('photo', models.BigIntegerField(max_length=12, null=True)),
                ('tel', models.BigIntegerField(max_length=11, null=True)),
                ('QQ', models.BigIntegerField(max_length=18, null=True)),
                ('mail', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
