# Generated by Django 3.2.5 on 2021-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpowermanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='st_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.SmallIntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
