# Generated by Django 3.2.5 on 2021-07-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manpowermanage', '0003_auto_20210708_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='favor_lever',
            field=models.SmallIntegerField(null=True),
        ),
    ]
